CREATE TABLE user_information (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fullname TEXT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    user_password TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    about_user TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);