CREATE TYPE STACK_PREFERENCE AS ENUM (
    'Backend',
    'Frontend',
    'Full Stack'
);

CREATE TABLE user_information (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fullname TEXT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    user_password TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    profile_photo bytea NOT NULL,
    about_user TEXT NOT NULL,
    user_stack STACK_PREFERENCE NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);