CREATE TABLE fluent_posts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT
        REFERENCES user_information(username) ON DELETE CASCADE NOT NULL,
    post_description TEXT,
    post_live_link TEXT,
    post_repository TEXT,
    post_image bytea NOT NULL,
    tech_stack TEXT,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    user_id INTEGER
        REFERENCES user_information(id) ON DELETE CASCADE NOT NULL
);