CREATE TABLE following (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    following_id INTEGER
        REFERENCES user_information(id) ON DELETE CASCADE NOT NULL,
    users_id INTEGER
        REFERENCES user_information(id) ON DELETE CASCADE NOT NULL
);
